[build]
  functions = "functions"   # Gibt an, dass der "functions"-Ordner f체r die Serverless-Funktionen verwendet wird.
  publish = "public"        # Gibt den Ordner an, in dem die statischen Dateien (wie index.html) gespeichert sind.

[dev]
  functions = "functions"   # Auch f체r den lokalen Entwicklungsserver
  publish = "public"        # Der statische Ordner
  port = 8888               # Der Port, auf dem der lokale Server l채uft (kann ge채ndert werden)