[build]
  functions = ".netlify/functions"  # Zeigt Netlify, wo die Funktionen zu finden sind
  publish = "public"  # Verzeichnis, das die statischen Dateien enthält

[[redirects]]
  from = "/register"
  to = "/.netlify/functions/index/register"
  status = 200

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/index/login"
  status = 200

[[redirects]]
  from = "/verifizierung"
  to = "/.netlify/functions/index/verifizierung"
  status = 200

[[redirects]]
  from = "/lernseterstellung"
  to = "/.netlify/functions/index/lernseterstellung"
  status = 200

[[redirects]]
  from = "/import"
  to = "/.netlify/functions/index/import"
  status = 200

[[redirects]]
  from = "/lernen"
  to = "/.netlify/functions/index/lernen"
  status = 200

[[redirects]]
  from = "/updateLernstand"
  to = "/.netlify/functions/index/updateLernstand"
  status = 200

[[redirects]]
  from = "/resetLernstand"
  to = "/.netlify/functions/index/resetLernstand"
  status = 200

[[redirects]]
  from = "/lernsetName"
  to = "/.netlify/functions/index/lernsetName"
  status = 200

[[redirects]]
  from = "/ordnererstellung"
  to = "/.netlify/functions/index/ordnererstellung"
  status = 200

[[redirects]]
  from = "/getFolder"
  to = "/.netlify/functions/index/getFolder"
  status = 200

[[redirects]]
  from = "/getSet"
  to = "/.netlify/functions/index/getSet"
  status = 200

[[redirects]]
  from = "/updateusername"
  to = "/.netlify/functions/index/updateusername"
  status = 200

[[redirects]]
  from = "/updatepassword"
  to = "/.netlify/functions/index/updatepassword"
  status = 200

[[redirects]]
  from = "/deleteaccount"
  to = "/.netlify/functions/index/deleteaccount"
  status = 200

[[redirects]]
  from = "/getuserdata"
  to = "/.netlify/functions/index/getuserdata"
  status = 200